# Generated by Django 3.1.2 on 2021-08-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectviewed',
            options={'verbose_name_plural': 'Objects viewed'},
        ),
    ]
