# Generated by Django 3.1.2 on 2021-08-22 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20210822_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectviewed',
            name='user',
        ),
    ]
