# Generated by Django 3.1.2 on 2021-08-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_objectviewed_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectviewed',
            name='user',
        ),
    ]
