# Generated by Django 3.1.2 on 2021-08-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_remove_objectviewed_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectviewed',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
