# Generated by Django 3.1.2 on 2021-08-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('content', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('top_3', models.BooleanField(default=False)),
                ('posted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('cities', models.ManyToManyField(blank=True, to='stories.City')),
                ('themes', models.ManyToManyField(to='stories.Themes')),
            ],
        ),
    ]
