# Generated by Django 3.1.2 on 2021-08-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='images')),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ManyToManyField(blank=True, to='stories.Image'),
        ),
    ]
