# Generated by Django 3.1.2 on 2021-08-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20210821_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='image',
        ),
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='images'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
