# Generated by Django 3.1.2 on 2021-08-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20210821_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='main_image',
            field=models.ImageField(default='default.png', null=True, upload_to='images'),
        ),
    ]
