# Generated by Django 3.1.2 on 2021-08-21 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_story_main_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='image',
            new_name='images',
        ),
    ]
