# Generated by Django 3.1.2 on 2021-08-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_auto_20210822_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'Stories'},
        ),
        migrations.AlterModelOptions(
            name='themes',
            options={'verbose_name_plural': 'Themes'},
        ),
    ]
