# Generated by Django 3.1.2 on 2021-08-26 11:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_auto_20210825_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
