# Generated by Django 3.1.2 on 2021-08-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0014_auto_20210827_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
